model:
  family: deberta
  name: microsoft/deberta-v3-large
context:
  type: sentence
rag:
  enabled: True
training:
  batch_size: 16
  gradient_checkpointing: True
  learning_rate: 3e-6
  weight_decay: 0.1
